### ISSUE TITLE
account - group filtering - warning window when no match

### ISSUE THREAD

**Issue by hodovska** [mhatina/openlmi_gui#10]
Performed steps:
1, Sign up to valid system
2, Select Account tab, and then select Groups tab
3, Press filter button
4, Insert non existing group name to Group name field
5, Press reload button.

Expected result:
No group found

Actual result:
Warning window appears:
![groupfiltering](https://cloud.githubusercontent.com/assets/9335600/6440666/b30627ca-c0df-11e4-98e7-d5d83d9cda23.png)

**Comment by mhatina** [comment]
Status: ON_QA

**Comment by hodovska** [comment]
fixed
