### ISSUE TITLE
Service - services count increases after reload

### ISSUE THREAD

**Issue by hodovska** [mhatina/openlmi_gui#12]
Performed steps:
1, Sing up to a valid system (e.g to localhost as root)
2, Choose Service tab 
3, If it is needed press reload to see services
4, Note count of services shown at the bottom of the screen
5, Reload again

Expected result:
The number of services is same as before

Actual result:
The number doubles

Before reload:

![servicecount1](https://cloud.githubusercontent.com/assets/9335600/6651460/37d4910a-ca43-11e4-9ea5-184989a22c8a.png)

After reload:

![servicecount2](https://cloud.githubusercontent.com/assets/9335600/6651461/3ed8dc9a-ca43-11e4-90e3-4f326d6d10fa.png)

**Comment by mhatina** [comment]
Status: ON_QA

**Comment by hodovska** [comment]
Tested correctly
