### ISSUE TITLE
Account - group deletion - inconsistency while deleting in sorted list

### ISSUE THREAD

**Issue by hodovska** [mhatina/openlmi_gui#13]
Performed steps:
1, Sing up to a valid system (e.g to localhost as root)
2, Select Account tab 
3, If it is needed press reload to see users
4, Select Groups tab
5, Sort groups by clicking on Name
6, Delete a group by right-clicking and selecting Delete user/group
7 Apply changes by pressing apply button

Expected result:
 - Group is deleted and other groups are shown correctly

Actual result:
 - Group is deleted, but there are not shown some values in other groups; see screenshot:
![sortedgroups-delete](https://cloud.githubusercontent.com/assets/9335600/6916845/ba6e7676-d79f-11e4-8eb1-0082a70ba29a.png)

**Comment by mhatina** [comment]
Status: ON_QA

**Comment by hodovska** [comment]
Tested correctly
