### ISSUE TITLE
Hardware - name of hardware group not readable

### ISSUE THREAD

**Issue by hodovska** [mhatina/openlmi_gui#14]
Steps:
1, try to read hardware labels on the left side of plugin window
2, move cursor above 5th item in list and try to read its whole name

Result:
It is not possible

![nameofhardware](https://cloud.githubusercontent.com/assets/9335600/7376711/e5bb24fc-ede1-11e4-97dd-d893dad9453b.png)

**Comment by mhatina** [comment]
Status: ON_QA (fixed only for bc branch)

**Comment by hodovska** [comment]
Tested Correctly
