### ISSUE TITLE
User Adding - possible to add user with no name

### ISSUE THREAD

**Issue by hodovska** [mhatina/openlmi_gui#8]
Steps:
1, Add system (e.g. localhost), select account tab and open new user dialog by right clicking user table and selecting Create new user/group
2, Fill/erase no values in new user dialog and click OK button

Expected behaviour:
- It is not possible to add user with no name set

Actual Behaviour:
- User is added to table
![added_mod](https://cloud.githubusercontent.com/assets/9335600/6318484/98ea3476-ba95-11e4-82f4-bb6b04673297.png)

Next steps:
- Apply changes by clicking apply button

Result:
-Warning appears
![error](https://cloud.githubusercontent.com/assets/9335600/6318489/d803d1e4-ba95-11e4-8f7a-58edf7229947.png)

**Comment by mhatina** [comment]
Status: ON_QA

**Comment by hodovska** [comment]
fixed
